---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
  namespace: jeevan
spec:
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: jeevanclk/email-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        livenessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: jeevan
spec:
  type: ClusterIP
  selector:
    app: email-service
  ports:
  - name: grpc
    port: 5000
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service
  namespace: jeevan
spec:
  selector:
    matchLabels:
      app: checkout-service
  template:
    metadata:
      labels:
        app: checkout-service
    spec:
      serviceAccountName: default
      containers:
      - name: server
        image: jeevanclk/checkout-service:latest
        ports:
        - containerPort: 5050
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:5050"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:5050"]
        env:
        - name: PORT
          value: "5050"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogue-service:3550"
        - name: SHIPPING_SERVICE_ADDR
          value: "shipping-service:50051"
        - name: PAYMENT_SERVICE_ADDR
          value: "payment-service:50051"
        - name: EMAIL_SERVICE_ADDR
          value: "email-service:5000"
        - name: CURRENCY_SERVICE_ADDR
          value: "currency-service:7000"
        - name: CART_SERVICE_ADDR
          value: "cart-service:7070"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-service
  namespace: jeevan
spec:
  type: ClusterIP
  selector:
    app: checkout-service
  ports:
  - name: grpc
    port: 5050
    targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
  namespace: jeevan
spec:
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: jeevanclk/recommendation-service:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        livenessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogue-service:3550"
        - name: DISABLE_PROFILER
          value: "1"
        resources:
          requests:
            cpu: 100m
            memory: 220Mi
          limits:
            cpu: 200m
            memory: 450Mi
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: jeevan
spec:
  type: ClusterIP
  selector:
    app: recommendation-service
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: jeevan
spec:
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: default
      containers:
      - name: server
        image: jeevanclk/frontend-service:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/_healthz"
            port: 8080
            httpHeaders:
            - name: "Cookie"
              value: "shop_session-id=x-readiness-probe"
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/_healthz"
            port: 8080
            httpHeaders:
            - name: "Cookie"
              value: "shop_session-id=x-liveness-probe"
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogue-service:3550"
        - name: CURRENCY_SERVICE_ADDR
          value: "currency-service:7000"
        - name: CART_SERVICE_ADDR
          value: "cart-service:7070"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "recommendation-service:8080"
        - name: SHIPPING_SERVICE_ADDR
          value: "shipping-service:50051"
        - name: CHECKOUT_SERVICE_ADDR
          value: "checkout-service:5050"
        - name: AD_SERVICE_ADDR
          value: "ad-service:9555"
        - name: ENABLE_PROFILER
          value: "0"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: jeevan
spec:
  type: NodePort
  selector:
    app: frontend-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-external
  namespace: jeevan
spec:
  type: LoadBalancer
  selector:
    app: frontend-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: jeevan
spec:
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: jeevanclk/payment-service:latest
        ports:
        - containerPort: 50051
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        env:
        - name: PORT
          value: "50051"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: jeevan
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad-service
  namespace: jeevan
spec:
  selector:
    matchLabels:
      app: ad-service
  template:
    metadata:
      labels:
        app: ad-service
    spec:
      serviceAccountName: default
      containers:
      - name: server
        image: jeevanclk/ad-service:latest
        ports:
        - containerPort: 9555
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9555"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9555"]
        env:
        - name: PORT
          value: "9555"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ad-service
  namespace: jeevan
spec:
  type: ClusterIP
  selector:
    app: ad-service
  ports:
  - name: grpc
    port: 9555
    targetPort: 9555
